apiVersion: v1
kind: Service
metadata:
    nsme: my-balancer
    namespace: my-namespace
spec:
    ports:
        - port: 80
          name: webport
          targetPort: 8080
    selector:
        app: go-web
    type: LoadBalancer
    loadBalancerIP: 10.10.130.145
