apiVersion : apps/v1
kind: Deployment
metadata:
        name: my-web-deployment-replicas
        labels:
                app : my-k8s-application
                env: prod
                owner: SerjioBorodulin
spec:
        replicas: 3
        selector:
                matchLabels:
                        project:
                                myproject2-repl
        template:
                metadata:
                        labels:
                                project:
                                        myproject2-repl
                spec:
                        containers:
                                - name : myproject2-repl-web
                                  image: svdevops07/myk8s_app:v0.2
                                  ports:
                                          - containerPort: 80
