apiVersion : apps/v1
kind: Deployment
metadata:
        name: my-web-deployment-autoscaling
        labels:
                app : my-k8s-application
                env: prod
                owner: SerjioBorodulin
spec:
        replicas: 2
        selector:
                matchLabels:
                        project:
                                myproject3-autosc
        template:
                metadata:
                        labels:
                                project:
                                        myproject3-autosc
                spec:
                        containers:
                                - name : myproject3-autosc-web
                                  image: svdevops07/myk8s_app:v0.2
                                  ports:
                                          - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
        name: my-autoscaling
spec:
        scaleTargetRef:
                apiVersion: apps/v2beta1v1
                kind: Deployment
                name: my-web-deployment-autoscaling
        minReplicas: 2
        maxReplicas: 5
        metrics:
        - type: Resource
          resource:
                name: cpu
                targetAverageUtilization: 70
        - type: Resource
          resource:
                name: memory
                targetAverageUtilization: 80
